# ATCOSIM Air Traffic Control Simulation Corpus
# Air traffic control communication corpus
# Lhotse recipe: https://lhotse.readthedocs.io/en/latest/datasets.html#atcosim

global_config:
  corpus_dir: ./data
  output_dir: ./manifests
  force_download: false
  
  # Feature extraction configuration (fbank for ATC ASR)
  feature_type: fbank
  num_mel_bins: 80
  frame_length: 0.025
  frame_shift: 0.01
  sampling_rate: 16000
  
  # Storage and computation
  storage_type: lilcom_chunky
  num_jobs: 4
  device: cpu
  progress_bar: true

datasets:
  - name: atcosim
    download_params: {}
    
    process_params:
      # Special token handling
      silence_sym: ""
      breath_sym: ""
      foreign_sym: "<unk>"
      partial_sym: "<unk>"
      unknown_sym: "<unk>"

