# This American Life Podcast Corpus
# Podcast episodes for ASR and diarization
# Lhotse recipe: https://lhotse.readthedocs.io/en/latest/datasets.html#this-american-life

global_config:
  corpus_dir: ./data
  output_dir: ./manifests
  force_download: false
  
  # Feature extraction configuration (fbank for podcast ASR)
  feature_type: fbank
  num_mel_bins: 80
  frame_length: 0.025
  frame_shift: 0.01
  sampling_rate: 16000
  
  # Storage and computation
  storage_type: lilcom_chunky
  num_jobs: 4
  device: cpu
  progress_bar: true

datasets:
  - name: this_american_life
    download_params:
      # Metadata URL
      metadata_url: https://ipfs.io/ipfs/bafybeidyt3ch6t4dtu2ehdriod3jvuh34qu4pwjyoba2jrjpmqwckkr6q4/this_american_life.zip
      
      # Website URL
      website_url: https://thisamericanlife.org
    
    process_params: {}

