# TIMIT Acoustic-Phonetic Corpus
# Phone recognition dataset with detailed phonetic transcriptions
# Lhotse recipe: https://lhotse.readthedocs.io/en/latest/datasets.html#timit

global_config:
  corpus_dir: ./data
  output_dir: ./manifests
  force_download: false
  
  # Feature extraction configuration (MFCC for phone recognition)
  feature_type: mfcc
  num_mel_bins: 40
  num_ceps: 13
  frame_length: 0.025
  frame_shift: 0.01
  sampling_rate: 16000
  use_energy: true
  cepstral_lifter: 22
  
  # Storage and computation
  storage_type: lilcom_chunky
  num_jobs: 4
  device: cpu
  progress_bar: true

datasets:
  - name: timit
    download_params:
      # Base URL for download
      base_url: http://www.openslr.org/resources
    
    process_params:
      # Number of phoneme classes
      # Options: 48 (full set), 39 (reduced set)
      num_phones: 48

